server.port: 8081

spring:
  profiles.active: dev
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging.level.org.hibernate.type.descriptor.sql: TRACE
