spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/testdb
    username: testuser
    password: testpass
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: # Required value
    password: # Required value
    properties:
      mail.smtp.auth: true
      mail.smtp.timeout: 5000
      mail.smtp.starttls.enable: true
