server:
  port: 8081
  tomcat:
    max-http-form-post-size: 5MB

spring:
  profiles.active: local
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging.level.org.hibernate.type.descriptor.sql: TRACE

app.host: http://localhost:8081